# -*- coding: utf-8 -*-
"""IrisFlowerClassification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MD5Mp9WpOMyGuO-pl056kVS_8jtayGDG

# IMPORT LIBRARIES
"""

import numpy as np
import pandas as pd

"""# IMPORT DATA SET

"""

df =pd.read_csv("Iris.csv")

df

df.shape

df.info()

"""# DROPPING THE COLUMN

"""

df=df.drop(columns=["Id"])

df

df.head()

"""# Transforming Categorical Data into Numeric Data

"""

df["Species"].replace({"Iris-setosa":1,"Iris-versicolor":2,"Iris-virginica":3},inplace=True)

df

"""# Creating Arrays

"""

x=pd.DataFrame(df,columns=["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]).values

x

y=df.Species.values.reshape(-1,1)

y

"""# Importing necessary Libraries

"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

"""# Train Test Split

"""

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

x_train.shape

y_train.shape

k=6
knclr=KNeighborsClassifier(k)

"""# Training the model using KNN (K Nearest Neighbor)

"""

knclr

knclr.fit(x_train,y_train)

y_pred=knclr.predict(x_test)

metrics.accuracy_score(y_test,y_pred)*100